using AutoBogus;
using FakeItEasy;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Store.DataContext.Context;
using Store.WebAPI.Configuration;
using Store.WebAPI.Filters;
using Xunit;