-- Создать пользователей

DROP ROLE IF EXISTS "StoreDBAdmin";
CREATE ROLE "StoreDBAdmin" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	PASSWORD 'Store123'
	CONNECTION LIMIT -1;


DROP ROLE IF EXISTS "StoreDBUser";
CREATE ROLE "StoreDBUser" WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	PASSWORD 'Store123'
	CONNECTION LIMIT -1;

